In [1]:
from itertools import chain
import numpy as np
import pandas as pd
from math import sqrt
from random import randint, shuffle

In [2]:
def generate_array(length, threshold):
    """Generates array without duplicates"""
    array=[i for i in range(1,length+1)]
    shuffle(array)
    t=randint(1,round(len(array)*threshold))
    for i in range(t):
        array[randint(1,len(array)-1)]=np.nan
    return array

In [3]:
def remove_duplicates(array):
    unique,count=np.unique(array, return_counts=1)
    m=np.isin(array,unique[count>1])
    array[m]=np.nan
    return array

In [4]:
def check_duplicates_sqr(sudoku):
    shape=round(sqrt(sudoku.shape[0])) ## should be even
    l=[np.hsplit(i,shape) for i in np.split(sudoku,shape)]
    a=[]
    for i in range(len(l)):
        LoL=[remove_duplicates(np.array(list(chain(*i)))) for i in l[i]]
        LoL_chunks=[np.split(i,shape) for i in LoL]
        lines=np.array([list(chain(*[j[a] for j in LoL_chunks])) for a in range(shape)])
        a.append(lines)
        sudoku=np.concatenate(a)
    return sudoku

In [5]:
def generate_sudoku(shape,threshold):
    """Generate sudoku with desired shape"""
    try:
        if (
            isinstance(shape,list) &
            isinstance(shape[0],int) &
            isinstance(shape[1],int)
        ):
            md_array=np.array([generate_array(length=shape[0], threshold=threshold) for i in range(shape[1])])
            md_array=np.transpose(md_array)
            md_array=np.array([remove_duplicates(i) for i in md_array])
            sudoku=pd.DataFrame(check_duplicates_sqr(md_array))
            sudoku[pd.isna(sudoku)]=''
            return sudoku
    except Exception as e:
        print(
            'shape should be a 2 len list of ints. with the required matrix shape.',
            e
        )

In [11]:
M=generate_sudoku([9,9],0.9)
M

   0  1  2  3 4  5  6  7  8
0  6  1  9  8    7
1        5             9
2                3        8
3  1
4     3     2          6
5                8  2  7
6  7  5                4
7
8  9  8  2             3